spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc.batch_size: 100
        default_fetch_size: 100
        order_inserts: true
        order_updates: true
      jakarta:
        persistence:
          sharedCache.mode: ALL
---
spring:
  config:
    activate:
      on-profile: "db-local"

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3308/kotlin_board?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: secret
      max-lifetime: 60000
      connection-timeout: 3000
      maximum-pool-size: 10